import type { CapitalEntry, DailyReview, Trade, TradingAccount } from '../sampleData';

function triggerDownload(content: BlobPart, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function csvCell(value: unknown): string {
  return `"${String(value ?? '').replaceAll('"', '""')}"`;
}

export function downloadTradesCsv(trades: Trade[], accounts: TradingAccount[]) {
  const accountMap = new Map(accounts.map((account) => [account.id, account.name]));
  const headers = ['Date','Account','Market','Instrument','Direction','Strategy','Entry','Exit','Quantity','Gross P&L','Charges','Net P&L','Rules followed','Emotion','Notes'];
  const rows = trades.map((trade) => [
    trade.date,
    accountMap.get(trade.accountId) || '',
    trade.market,
    trade.instrument,
    trade.direction,
    trade.strategy,
    trade.entry,
    trade.exit,
    trade.quantity,
    trade.grossPnl,
    trade.charges,
    trade.pnl,
    trade.followedRules ? 'Yes' : 'No',
    trade.emotion,
    trade.notes,
  ]);
  triggerDownload(
    [headers, ...rows].map((row) => row.map(csvCell).join(',')).join('\n'),
    `tickmint-trades-${new Date().toISOString().slice(0,10)}.csv`,
    'text/csv;charset=utf-8',
  );
}

export function downloadWorkspaceBackup(data: {
  profileName: string;
  accounts: TradingAccount[];
  trades: Trade[];
  capitalEntries: CapitalEntry[];
  reviews: DailyReview[];
}) {
  triggerDownload(
    JSON.stringify({ product:'TickMint', version:'Phase 2A Release Candidate', exportedAt:new Date().toISOString(), ...data }, null, 2),
    `tickmint-backup-${new Date().toISOString().slice(0,10)}.json`,
    'application/json',
  );
}

export function printPerformanceReport(summary: Record<string, unknown>, instrumentData: Array<Record<string, unknown>>) {
  const reportWindow = window.open('', '_blank', 'noopener,noreferrer');
  if (!reportWindow) return;
  const metrics = Object.entries(summary).map(([key,value]) => `<tr><th>${key}</th><td>${value}</td></tr>`).join('');
  const instruments = instrumentData.map((row) => `<tr><td>${row.name ?? ''}</td><td>${row.trades ?? 0}</td><td>${row.winRate ?? 0}%</td><td>${row.pnl ?? 0}</td></tr>`).join('');
  reportWindow.document.write(`<!doctype html><html><head><title>TickMint Performance Report</title><style>
  body{font-family:Inter,Arial,sans-serif;color:#111827;margin:40px}header{border-bottom:2px solid #274c77;padding-bottom:18px;margin-bottom:28px}
  h1{margin:0;font-size:30px}p{color:#667085}table{width:100%;border-collapse:collapse;margin:18px 0 32px}
  th,td{padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:left}th{color:#475467;background:#f8fafc}
  footer{margin-top:36px;color:#98a2b3;font-size:12px}@media print{button{display:none}body{margin:18mm}}</style></head><body>
  <header><h1>TickMint Performance Report</h1><p>Trading journal and performance review</p></header>
  <h2>Summary</h2><table>${metrics}</table>
  <h2>Instrument performance</h2><table><thead><tr><th>Instrument</th><th>Trades</th><th>Win rate</th><th>Net P&L</th></tr></thead><tbody>${instruments}</tbody></table>
  <button onclick="window.print()">Print / Save as PDF</button><footer>Generated by TickMint. This is not investment advice.</footer>
  </body></html>`);
  reportWindow.document.close();
}
